[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
archie_cpi = "81JFbU5xub73UmkJFgUG2KTDLvtx9o7Kq8iK3hJFnEn9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
